version: '3.8'
services:
    # postman_collection:
    #   container_name: postman_docker_container
    #   build:
    #     context: ./postman
    #     dockerfile: Dockerfile
    #   command:
    #     run https://www.getpostman.com/collections/f4647fd6257e8af43303
    #     --folder "Environment Variables Example"
    #     -r html,cli
    #     --reporter-html-export reports/Main_Report.html
    #   volumes:
    #     - ./postman:/etc/newman
    db:
        container_name: db
        restart: always
        build:
            context: ./db
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    php-apache:
        container_name: php-apache
        build:
          context: ./php
        ports:
            - '80:80'
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        volumes:
          - ./app:/var/www/laravel_docker
          - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
          - db